### ISSUE TITLE
Kill All Process Expect One !

### ISSUE THREAD

**Issue by Nebula-Spark** [davidcoleman007/ps4js#1]
Hi ,
I just want to Kill all running process in windows ,

example
like kill all process expect chrome.exe
Is there anyway to Do this ?

btw i am just newbie here ,

it would be great if u can give any solution for this ,

**Comment by davidcoleman007** [comment]
Hey, sorry I didn't get to answering this sooner.  Never got a notification of your issue.  Will check my settings.

combine the 2 examples in the Readme

```javascript
var ps = require('ps4js');

ps.list(function(err, results) {
  if (err)
    throw new Error( err );

  results.map(item=>{
    if(item.command != 'chrome.exe') {
      ps.kill(item.pid, function(err, stdout) {
        if (err) {
          console.log('could not kill pid '+this.pid);
        }
      }.bind(item));
    }
  });
});
```

**Comment by Nebula-Spark** [comment]
@davidcoleman007 
 Last  2 months i was looking for a solution and couldn't find anything and finally used some batch-script   But Now !
Even the Response was  too late But  Perfect 👍 

It's Working like a MAGIC !!
You Are My Savior ,
Thank you very Much :)
